name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        # choose node.js version to use
        node-version: '14'

    # cache node_modules
    - name: Cache dependencies
      uses: actions/cache@v2
      id: yarn-cache
      with:
        path: |
          **/node_modules
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-*

    # Create env file for Telegram bot about hatid and botkey 
    - name: 'Create env file'
      run: |
        touch .env
        echo CHATID=${{ secrets.CHATID }}  >> .env
        echo BOTKEY="${{ secrets.BOTKEY }}"  >> .env
        cat .env

    # install dependencies if the cache did not hit
    - name: Install dependencies
      run: yarn install

    # run build script
    - name: Build VuePress site
      run: yarn docs:build
      working-directory: ./docs/.vuepress/dist/

    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.MY_PRIVATE_KEY_DEPLOY }}
        known_hosts: 'just-a-placeholder-so-we-dont-get-errors'

    - name: Adding Known Hosts
      run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy with rsync
      run: rsync -avz ./docs/.vuepress/dist/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/html/personal/
